/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // ─── Sovereign Institutional Palette ────────────────────────────────
        surface: {
          DEFAULT: '#faf9f5',
          dim: '#dbdad6',
          bright: '#faf9f5',
          lowest: '#ffffff',
          low: '#f4f4f0',
          mid: '#efeeea',
          high: '#e9e8e4',
          highest: '#e3e2df',
        },
        primary: {
          DEFAULT: '#003527',
          container: '#064e3b',
          fixed: '#b0f0d6',
          'fixed-dim': '#95d3ba',
          inverse: '#95d3ba',
          on: '#ffffff',
          'on-container': '#80bea6',
          'on-fixed': '#002117',
          'on-fixed-variant': '#0b513d',
        },
        secondary: {
          DEFAULT: '#735c00',
          container: '#fed65b',
          fixed: '#ffe088',
          'fixed-dim': '#e9c349',
          on: '#ffffff',
          'on-container': '#745c00',
          'on-fixed': '#241a00',
          'on-fixed-variant': '#574500',
        },
        tertiary: {
          DEFAULT: '#262e42',
          container: '#3c4459',
          fixed: '#dae2fd',
          'fixed-dim': '#bec6e0',
          on: '#ffffff',
          'on-container': '#aab1ca',
          'on-fixed': '#131b2e',
          'on-fixed-variant': '#3f465c',
        },
        outline: { DEFAULT: '#707974', variant: '#bfc9c3' },
        'on-surface': { DEFAULT: '#1b1c1a', variant: '#404944' },
        error: { DEFAULT: '#ba1a1a', container: '#ffdad6', on: '#ffffff', 'on-container': '#93000a' },
      },
      fontFamily: {
        display: ['Newsreader', 'Georgia', 'serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['60px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: { unit: '8px' },
      maxWidth: { container: '1440px' },
      boxShadow: {
        card: '0px 4px 20px rgba(0,0,0,0.04)',
        'card-hover': '0px 8px 32px rgba(0,0,0,0.08)',
        glass: '0px 2px 12px rgba(0,0,0,0.06)',
        emerald: '0 0 0 3px rgba(0,53,39,0.15)',
        gold: '0 0 0 3px rgba(115,92,0,0.2)',
      },
      backdropBlur: { glass: '20px' },
      backgroundImage: {
        'emerald-gradient': 'linear-gradient(135deg, #003527 0%, #064e3b 100%)',
        'ivory-texture': "url(\"data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='0.015'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E\")",
      },
      animation: {
        'fade-in': 'fadeIn 0.4s ease-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'slide-in-right': 'slideInRight 0.3s ease-out',
        'pulse-gold': 'pulseGold 2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideInRight: { from: { opacity: '0', transform: 'translateX(16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        pulseGold: { '0%, 100%': { boxShadow: '0 0 0 0 rgba(115,92,0,0.3)' }, '50%': { boxShadow: '0 0 0 6px rgba(115,92,0,0)' } },
      },
    },
  },
  plugins: [],
};
